[[admin-guide-iptables]]
= iptables
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview
There are many system components including {product-title}, containers, and
software that manage local firewall policies that rely on the kernel iptables
configuration for proper network operation. In addition, the iptables
configuration of all nodes in the cluster must be correct for networking to
work.

All components independently work with iptables without knowledge of how other
components are using them. This makes it very easy for one component to break
another component's configuration. Further, {product-title} and the Docker service
assume that iptables remains set up exactly as they have set it up. They may not
detect changes introduced by other components and if they do there may be some
lag in implementing the fix. In particular, {product-title} does monitor and fix
problems. However, the Docker service does not.

== Restarting
Docker doesn't monitor the iptables rules that it adds for exposing ports from containers and hence if
iptables service is restarted, then these rules are lost. So, to safely restart iptables, it is
recommended that the rules are saved and restored.

----
# systemctl restart iptables.service
# systemctl restart docker
# systemctl restart atomic-openshift-node.service
----
