[[admin-guide-securing-builds]]
= Securing Builds by Strategy
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview

xref:../architecture/core_concepts/builds_and_image_streams.adoc#builds[Builds]
in {product-title} are run in
xref:../install_config/install/prerequisites.adoc#security-warning[privileged containers] that
have access to the Docker daemon socket. As a security measure, it is
recommended to limit who can run builds and the strategy that is used for those
builds.
xref:../architecture/core_concepts/builds_and_image_streams.adoc#custom-build[Custom
builds] are inherently less safe than
xref:../architecture/core_concepts/builds_and_image_streams.adoc#source-build[Source
builds], given that they can execute any code in the build with potentially full
access to the node's Docker socket, and as such are disabled by default.  xref:../architecture/core_concepts/builds_and_image_streams.adoc#docker-build[Docker
build] permission should also be granted with caution as a vulnerability in the Docker build
logic could result in a privileges being granted on the host node.

By default, all users that can create builds are granted permission to use the
Docker and Source-to-Image build strategies. Users with xref:../architecture/additional_concepts/authorization.adoc#roles[*cluster-admin*]
privileges can enable the Custom build strategy, as referenced in the xref:restricting-build-strategies-to-a-user-globally[Restricting Build Strategies to a User Globally]
section of this page.

You can control who can build with what build strategy using an
xref:../architecture/additional_concepts/authorization.adoc#architecture-additional-concepts-authorization[authorization
policy]. Each build strategy has a corresponding build subresource.
A user must have permission to create a build _and_ permission to create
on the build strategy subresource in order to create builds using that strategy.
Default roles are provided which grant the *create* permission on the build strategy subresource.

.Build Strategy Subresources and Roles
[options="header"]
=======
By default, project administrators (the
xref:../architecture/additional_concepts/authorization.adoc#roles[*admin* role])
and project editors (the
xref:../architecture/additional_concepts/authorization.adoc#roles[*edit* role])
are granted permission to use all build strategies (Docker, Source-to-Image, and
Custom).

You can control who can build with what build strategy using an
xref:../architecture/additional_concepts/authorization.adoc#architecture-additional-concepts-authorization[authorization
policy]. Each build strategy has a corresponding build subresource. Granting
permission to *create* on the build subresource allows the user to create builds
of that type.

.Build Strategy Subresources
[cols="1,1",options="header"]
>>>>>>> openshift/online
|===

|Strategy |Subresource |Role

|Docker
|builds/docker
|system:build-strategy-docker

|Source-to-Image
|builds/source
|system:build-strategy-source

|Custom
|builds/custom
|system:build-strategy-custom

|Custom
|builds/jenkinspipeline
|system:build-strategy-jenkinspipeline

|===

[[disabling-a-build-strategy-globally]]
== Disabling a Build Strategy Globally
To prevent access to a particular build strategy globally, log in as a user with
xref:../architecture/additional_concepts/authorization.adoc#roles[*cluster-admin*]
privileges and edit each of the default roles:

----
$ oc edit clusterrole admin
$ oc edit clusterrole edit
----

For each role, remove the line that corresponds to the resource of the strategy to disable.

.Disable the Docker Build Strategy for *admin*
=====

----
kind: ClusterRole
metadata:
  name: admin
...
rules:
- resources:
  - builds/custom
  - builds/docker <1>
  - builds/source
  ...
...
----
<1> Delete this line to disable Docker builds globally for users with the *admin* role.
=====

[[restricting-build-strategies-to-a-user-globally]]

== Restricting Build Strategies to a User Globally

To allow only a set of specific users to create builds with a particular strategy:

. xref:disabling-a-build-strategy-globally[Remove the build strategy
subresource from the default *admin* and *edit* roles].

. Assign the role corresponding to the build strategy to a specific user.
For example, to add the *system:build-strategy-docker* cluster role to the user *devuser*:
+
====
----
$ oadm policy add-cluster-role-to-user system:build-strategy-docker devuser
----
====

[WARNING]
====
Granting a user access at the cluster level to the *builds/docker* subresource
means that the user will be able to create builds with the Docker strategy in
any project in which they can create builds.
====

[[restricting-build-strategies-to-a-user-within-a-project]]

== Restricting Build Strategies to a User Within a Project

Similar to granting the build strategy role to a user globally, to allow only a
set of specific users within a project to create builds with a particular
strategy:

. xref:disabling-a-build-strategy-globally[Remove the build strategy resource
from the default *admin* and *edit* roles].
. xref:create-separate-role[Create a separate role for that build strategy.]
. Assign the role to a specific user within a project. For example, to add the
new *dockerbuilder* role within the project *devproject* to the user *devuser*:
+
====
----
$ oadm policy add-role-to-user system:build-strategy-docker devuser -n devproject
----
====
